@startuml

title Kernel

class KernelMain {
    +KernelMain()
}

class Buffer {
    +buf()
    +out()
}

class Memory {
    +allocate()
    +free()
}

class Palette {
    +set()
    {static}+simplePalette()
}

class Screen {
    +shape()
    +text()
    +image()
    +drawBack()
}

class TextDrawer {
    +putfonts8_asc()
    -putfont8()
}

class ShapeDrawer {
    +boxFill8()
}

class CharImageDrawer {
    +mouse()
}

class Segment {
    +setKernelSegment()
}

class SegmentDescriptorTable {
    +add()
    +at()
}

class Interupt {
}

class InteruptDescriptorTable {
    +add()
}

KernelMain --> Screen
KernelMain --> Memory
KernelMain --> Palette
KernelMain --> Segment
KernelMain --> Interupt
Screen "1" *-- "1" TextDrawer
Screen "1" *-- "1" ShapeDrawer
Screen "1" *-- "1" CharImageDrawer
Segment "1" *-- "1" SegmentDescriptorTable
Interupt "1" *-- "1" InteruptDescriptorTable

@enduml